// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { HelloError, HelloResponse, LoginError, LoginResponse, ListNotesError, ListNotesResponse, RegisterError, RegisterResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Get a hello message.
 */
export const hello = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<HelloResponse, HelloError, ThrowOnError>({
    ...options,
    url: '/hello'
}); };

/**
 * Login to the application.
 */
export const login = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).post<LoginResponse, LoginError, ThrowOnError>({
    ...options,
    url: '/login'
}); };

/**
 * List all notes for the authenticated user.
 */
export const listNotes = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<ListNotesResponse, ListNotesError, ThrowOnError>({
    ...options,
    url: '/notes'
}); };

/**
 * Register a new user.
 */
export const register = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).post<RegisterResponse, RegisterError, ThrowOnError>({
    ...options,
    url: '/register'
}); };