// This file is auto-generated by @hey-api/openapi-ts

export type HelloResponse = ({
    message?: string;
});

export type HelloError = unknown;

export type LoginResponse = ({
    token?: string;
});

export type LoginError = ({
    message?: string;
});

export type ListNotesResponse = (Array<{
    id?: string;
    text?: string;
}>);

export type ListNotesError = ({
    message?: string;
});

export type RegisterResponse = ({
    message?: string;
});

export type RegisterError = ({
    message?: string;
});